# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8423dcbf8c9dd6ccbe0f644b99bbe1bfcfb38b6ba6ed9af8fef347056ad63c96750561dcaa0fe5d4d2b5722f8678e3aace4049eafdfc483a7fa8410d8fa1f75

test:
  secret_key_base: 02c9c045e1620d299761ce97a8c0b139885f822c8c7af8d09ae4b86ea00fd6824c429e7ecc131308b296f1e83b7b7b2f814a851ce7c209f22d31b6d95aa446f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
